enum InvoiceType {
  SATIS = 'SATIS',
  IADE = 'IADE',
  TEVKIFAT = 'TEVKIFAT',
  ISTISNA = 'ISTISNA',
  OZEL_MATRAH = 'OZELMATRAH',
  IHRAC_KAYITLI = 'IHRACKAYITLI',
  HAL_TIPI_FATURA_SATIS = 'HKSSATIS',
  HAL_TIPI_FATURA_KOMISYONCU = 'HKSKOMISYONCU'
}

export default InvoiceType
