name: Publish Docker image

on:
  push:
    tags:
      - 'e-fatura-cli@*'

env:
  IMAGE_NAME: e-fatura
  TARGET_PLATFORMS: linux/amd64,linux/arm64
  DOCKERHUB_USERNAME: bilaleren

jobs:
  cli_package_info:
    name: Get CLI package info
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.version.outputs.name }}
      version: ${{ steps.version.outputs.version }}
      description: ${{ steps.version.outputs.description }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: version
        run: |
          apt-get install jq -y &&
          echo "name=$(cat ./packages/e-fatura-cli/package.json | jq -r '.name')" >> "$GITHUB_OUTPUT" &&
          echo "version=$(cat ./packages/e-fatura-cli/package.json | jq -r '.version')" >> "$GITHUB_OUTPUT" &&
          echo "description=$(cat ./packages/e-fatura-cli/package.json | jq -r '.description')" >> "$GITHUB_OUTPUT"

  publish_image_to_docker_hub:
    name: Publish image to DockerHUB
    needs: cli_package_info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHUB
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push latest image to DockerHUB
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./latest.dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          labels: |
            org.opencontainers.image.source="${{ github.server_url }}/${{ github.repository }}"
          platforms: ${{ env.TARGET_PLATFORMS }}

      - name: Build and push v${{ needs.cli_package_info.outputs.version }} image to DockerHUB
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            CLI_PACKAGE_VERSION=${{ needs.cli_package_info.outputs.version }}
          file: ./version.dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.cli_package_info.outputs.version }}
          labels: |
            org.opencontainers.image.source="${{ github.server_url }}/${{ github.repository }}"
          platforms: ${{ env.TARGET_PLATFORMS }}

      - name: DockerHub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          readme-filepath: ./packages/e-fatura-cli/DOCKER_README.md
