name: Publish Docker image

on:
  push:
    tags:
      - 'e-fatura-cli@*'

env:
  IMAGE_NAME: e-fatura
  TARGET_PLATFORMS: linux/amd64,linux/arm64
  DOCKERHUB_USERNAME: bilaleren

jobs:
  cli-package-info:
    name: Get CLI package info
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.info.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - id: info
        run: |
          echo "version=$(node -pe "require('./packages/e-fatura-cli/package.json').version")" >> $GITHUB_OUTPUT

  publish-image:
    name: Publish image to DockerHUB
    needs:
      - cli-package-info
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHUB
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image to DockerHUB
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            CLI_PACKAGE_VERSION=${{ needs.cli-package-info.outputs.version }}
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.cli-package-info.outputs.version }}
          platforms: ${{ env.TARGET_PLATFORMS }}

      - name: DockerHub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          readme-filepath: ./packages/e-fatura-cli/DOCKER_README.md
